// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pedido.Data;

#nullable disable

namespace WebApplicationPedido.Migrations
{
    [DbContext(typeof(PedidoDbContext))]
    [Migration("20231119015429_alteradarelacoes2")]
    partial class alteradarelacoes2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("CondimentoProduto", b =>
                {
                    b.Property<int>("CondimentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CondimentoId", "ProdutosId");

                    b.HasIndex("ProdutosId");

                    b.ToTable("CondimentoProduto");
                });

            modelBuilder.Entity("Pedido.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Pedido.Models.Condimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<float>("Quantidade")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Condimento");
                });

            modelBuilder.Entity("Pedido.Models.Desconto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Desconto");
                });

            modelBuilder.Entity("Pedido.Models.Garcom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cracha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Garcom");
                });

            modelBuilder.Entity("Pedido.Models.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DescontoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GarcomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MesaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PagamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SomaTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaxaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DescontoId");

                    b.HasIndex("GarcomId");

                    b.HasIndex("MesaId");

                    b.HasIndex("PagamentoId");

                    b.HasIndex("TaxaId");

                    b.ToTable("Lista");
                });

            modelBuilder.Entity("Pedido.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Disponibilidade")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mesa");
                });

            modelBuilder.Entity("Pedido.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Formadepagamento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("Pedido.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ListaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<float>("PrecoTotal")
                        .HasColumnType("REAL");

                    b.Property<float>("PrecoUnit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ListaId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Pedido.Models.Taxa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<float>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Taxa");
                });

            modelBuilder.Entity("CondimentoProduto", b =>
                {
                    b.HasOne("Pedido.Models.Condimento", null)
                        .WithMany()
                        .HasForeignKey("CondimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pedido.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pedido.Models.Lista", b =>
                {
                    b.HasOne("Pedido.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Pedido.Models.Desconto", "Desconto")
                        .WithMany()
                        .HasForeignKey("DescontoId");

                    b.HasOne("Pedido.Models.Garcom", "Garcom")
                        .WithMany()
                        .HasForeignKey("GarcomId");

                    b.HasOne("Pedido.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId");

                    b.HasOne("Pedido.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId");

                    b.HasOne("Pedido.Models.Taxa", "Taxa")
                        .WithMany()
                        .HasForeignKey("TaxaId");

                    b.Navigation("Cliente");

                    b.Navigation("Desconto");

                    b.Navigation("Garcom");

                    b.Navigation("Mesa");

                    b.Navigation("Pagamento");

                    b.Navigation("Taxa");
                });

            modelBuilder.Entity("Pedido.Models.Produto", b =>
                {
                    b.HasOne("Pedido.Models.Lista", null)
                        .WithMany("Produtos")
                        .HasForeignKey("ListaId");
                });

            modelBuilder.Entity("Pedido.Models.Lista", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
